### ISSUE TITLE
Text disapear when hover the button to edit a contact

### ISSUE THREAD

**Issue by Bagu** [EstudioNexos/mabola#1]
This code :

input.button.mainaction,
.formbuttons input.button,
input.button,
.pagenav.dark a.button,
.pagenav a.button,
a.button, .buttongroup {
    background: #eee none repeat scroll 0 0;
    border: none medium;
    border-radius: 2px;
    box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12);
    transition: box-shadow 0.2s cubic-bezier(0.4, 0, 1, 1) 0s, background-color 0.2s cubic-bezier(0.4, 0, 0.2, 1) 0s, color 0.2s cubic-bezier(0.4, 0, 0.2, 1) 0s;
    will-change: box-shadow, transform;
    color: #525252;
    text-shadow: none;
}

may be completed by : 

input.button.mainaction {
    color: #828282;
}

If not, the text disappear.

**Comment by n3storm** [comment]
Thanks. Final fix is:
input.button.mainaction:hover {
color: #828282;
}

Commit b7cc7d130c3598ef8daf5436b9a01f8006699f6c

:)
