### ISSUE TITLE
2FA issue

### ISSUE THREAD

**Issue by frezbo** [EstudioNexos/mabola#10]
twofactor_gauthenticator 2FA plugin not working with mabola skin, after entering the 2FA code it shows invalid.

**Comment by n3storm** [comment]
Can you provide server log message? (apache, php-fpm, nginx, ...)

Thanks in avance.

**Comment by frezbo** [comment]
> ## 
- [27/Apr/2016:09:05:46 +0530] "GET /roundcube/?_task=logout&_token=cfa1fb2cd41b55764bedaa84da99018e HTTP/1.1" 200 3027 "https://domain.com/roundcube/skins/mabola/styles.css?s=1460780902" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
- \- [27/Apr/2016:09:05:51 +0530] "POST /roundcube/ HTTP/1.1" 200 2905 "https://domain.com/roundcube/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
  117.211.164.84 - - [27/Apr/2016:09:05:52 +0530] "GET /roundcube/ HTTP/1.1" 200 2859 "https://domain.com/roundcube/skins/mabola/styles.css?s=1460780902" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
  - \- [27/Apr/2016:09:06:49 +0530] "POST /roundcube/ HTTP/1.1" 200 3313 "https://domain.com/roundcube/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
  - \- [27/Apr/2016:09:06:50 +0530] "GET /roundcube/ HTTP/1.1" 302 606 "https://domain.com/roundcube/skins/mabola/styles.css?s=1460780902" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
- \- [27/Apr/2016:09:06:50 +0530] "GET /roundcube/?_task=logout&_token=c8d1076a56fdb431d4248421af1d7d70 HTTP/1.1" 200 3026 "https://domain.com/roundcube/skins/mabola/styles.css?s=1460780902" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
- \- [27/Apr/2016:09:06:57 +0530] "POST /roundcube/ HTTP/1.1" 200 3047 "https://domain.com/roundcube/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
- \- [27/Apr/2016:09:06:58 +0530] "GET /roundcube/ HTTP/1.1" 200 2858 "https://domain.com/roundcube/skins/mabola/styles.css?s=1460780902" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
  127.0.0.1 - - [27/Apr/2016:09:07:12 +0530] "GET / HTTP/1.1" 302 373 "-" "monit/5.6"
  127.0.0.1 - - [27/Apr/2016:09:09:12 +0530] "GET / HTTP/1.1" 302 373 "-" "monit/5.6"
  >-

**Comment by frezbo** [comment]
progress????

**Comment by n3storm** [comment]
Hi @frezbo,

We don't have any Roundcube setup with 2FA third party plugin.

Would you be able to provide in private message your real url to check rendering or css errors? (we are not asking for user or passwords, only login url) 

Your issue is very strange as mabola theme has no PHP code or interaction, is only CSS and images.

**Comment by n3storm** [comment]
Is very unlikely this issue is related with a theme, but @frezbo  may find latest code could solve your issue because all theme files are retrieved throught https.

**Comment by frezbo** [comment]
I fixed the issue by downloading all the external fonts and placing them in a folder, and loading locally. I think the SAMEORIGIN policy prevented the loading of fonts
