### ISSUE TITLE
Error in configuration button

### ISSUE THREAD

**Issue by filhocf** [EstudioNexos/mabola#12]
Hi

Have some strange behavior with the config button. Follow the mabola and larry screens to see the problem.

![image](https://cloud.githubusercontent.com/assets/952596/17139660/c6dac876-531b-11e6-8fd6-cf29a0bc4940.png)

![image](https://cloud.githubusercontent.com/assets/952596/17139621/9cba2794-531b-11e6-8af7-48bf7ed28978.png)

**Comment by Pethical** [comment]
This is some as https://github.com/EstudioNexos/mabola/issues/11
The browser don't want to download http:// fonts on https connection. I sent a pull request.

**Comment by filhocf** [comment]
Hi

I found in line 54 of style.css this string: content: "\f085"; .  I commented it and removed the small box.

After, I removed 'display:none;' from line 217 and appeared the 'Configuration' text.

Can you test and update your code?

**Comment by n3storm** [comment]
Sorry, we are on summer holidays. We will solve this soon.

**Comment by n3storm** [comment]
Pull merged, closing this for now. Thanks everybody.
