### ISSUE TITLE
Add a icon for Thunderbird Labels plugin

### ISSUE THREAD

**Issue by filhocf** [EstudioNexos/mabola#16]
Please, can you make/build a icon for Roundcube Thunderbird plugins (https://github.com/rodrigo-castillo/roundcube-plugin-thunderbird-labels)?

![image](https://cloud.githubusercontent.com/assets/952596/17436669/1641da46-5aef-11e6-92fb-7347dbef360a.png)

**Comment by n3storm** [comment]
We are using this plugin too so we will add icon as soon as possible. Thanks!

**Comment by filhocf** [comment]
Any update?

**Comment by n3storm** [comment]
Ready in master @filhocf 

![seleccion_279](https://cloud.githubusercontent.com/assets/220748/22327553/14f9163e-e3b8-11e6-8366-c9e90b817201.png)

**Comment by filhocf** [comment]
\o/ Muchas gracias! :-D

**Comment by n3storm** [comment]
A vos!

**Comment by filhocf** [comment]
Sorry @n3storm , but I found more bugs.

![image](https://cloud.githubusercontent.com/assets/952596/22423994/9916ef60-e6db-11e6-9377-80f6f9c9ec38.png)

Take a look into Configuration > Preferences > Thunderbird Labels Options. This icon isn't updated. Only into toolbar in the main page.

Other problem is that after updating to RC 1.3.beta, your plugin isn't working correctly.
![image](https://cloud.githubusercontent.com/assets/952596/22424118/1b3deee4-e6dc-11e6-8b20-7933eb75a66c.png)

And for this problem, I haven't the solution. I select a email and the icon is disabled. I can't select the tag for there selected email.

**Comment by n3storm** [comment]
See #18

**Comment by filhocf** [comment]
Hola Nestor!

Unhappily, this is the same behavior in 1.2.0. Take a look in the picture. Behind the modal window, have some icons, where the penultimate is of tbird, in the config section.

![image](https://cloud.githubusercontent.com/assets/952596/22590007/5f4de722-e9f4-11e6-9d80-590a76ab1d1c.png)
 
I think that the problem is in https://github.com/EstudioNexos/mabola/blob/master/images/listicons.png that haven't a icon for tbird. Can you confirm, please?

**Comment by n3storm** [comment]
that is @filhocf :( we forgot to update listicons.png, please wait.

**Comment by filhocf** [comment]
Hi @n3storm 

Any update? Could be good reopen this issue?
