### ISSUE TITLE
Error in RC 1.3.x

### ISSUE THREAD

**Issue by filhocf** [EstudioNexos/mabola#18]
Updating my docker image with RC 1.3.beta, I found some strange behaviors. Take a look in the "Configuration" button in to toolbar.

![image](https://cloud.githubusercontent.com/assets/952596/22423846/d07ead18-e6da-11e6-9cd5-d4cb3dabed54.png)

The expected behavior is to show the word "Configuration" (Configuração in portuguese) and not a gear's icon.

**Comment by n3storm** [comment]
Hi filhocf, can you give us an email account (like dummy@whatever) to your setup?

We have not yet installed any RC 1.3beta.

Anyway we shoud wait till 1.3 is stable to fix anything IMHO

**Comment by filhocf** [comment]
Hi @n3storm 

So, I returned to see my env again. Was a hard time in my job in last months, but yesterday I could go back to my roundcube instance.

Taking a look into git of rc, I saw a [docker image](https://hub.docker.com/r/roundcube/roundcubemail/) and today I could start to play with the last version (1.3.3) in minutes. When I installed the mabola theme,  I saw that bug stay here.

Did you already update your env to 1.3.x ? If yes, haven't problems? Look my rc.
![image](https://user-images.githubusercontent.com/952596/34012753-1fec6ed2-e0fc-11e7-8942-eeaf87175384.png)

Yet with a gear in "Settings", where is wanted the text "Settings".

**Comment by filhocf** [comment]
@n3storm, I take a new look inside my env and I saw a "strange" (?) element.

![image](https://user-images.githubusercontent.com/952596/34040251-05fdf8d2-e17a-11e7-8462-2ddc5cc6c0dd.png)

Look in the highlighted line (blue) in code window. To "settings" element have a "::before == $0" that haven't for other elements, like "Contacts". I tried to track from where is this element (::before) without success.

Is the unique different element that I found. I hope that this element can help in find the bug.

**Comment by filhocf** [comment]
Hi @n3storm 
I had more one insight. I changed to larry theme again and taked a look in code other time.
Haven't that element "::before" into code of larry.
![image](https://user-images.githubusercontent.com/952596/34073971-f2107886-e28c-11e7-971b-c5ef95eaf2d3.png)
