### ISSUE TITLE
Theme not working?

### ISSUE THREAD

**Issue by rmulr** [EstudioNexos/mabola#19]
Hi there,

i am having problems getting this theme up and running.

Installed as described, and i selected the Mambola skin first uploded to the /skins directory through the users settings.

However it keeps using the Larry skin. Any idea?

I used Roundcube Webmail 1.2.4

**Comment by Kallb123** [comment]
Same problem here with both mabola and mabola-blue. I can select mabola but it just looks like Larry still. I can't even select mabola-blue it just switches back to Larry.

I'm using Roundcube 1.3.0.

**Comment by AdrianNoss** [comment]
You have to rename the extracted "mabola-master" folder to "mabola" in your skin folder. After that it works without any problems on 1.3.0.

**Comment by n3storm** [comment]
For 1.2.4 version it should work for you @lddd , give us some more information about what steps are you taking to install skin in case you are missing something.

As @AdrianNoss points out, skin folder has to be renamed. Also rename "mabola-blue-master" to "mabola-blue". This step is documented at How to install section in README.md file https://github.com/EstudioNexos/mabola/blob/master/README.md

Have in mind we are on our way to test and fix anything for Roundcube 1.3.0. We haven't done it yet.. We will update README to reflect 1.3.x support for this skin.

**Comment by n3storm** [comment]
Just checked Mabola is working with latest Roundcube 1.3.3
