### ISSUE TITLE
Empty space under the top bar

### ISSUE THREAD

**Issue by PF4Public** [EstudioNexos/mabola#5]
There's is an empty space under the top bar on settings tab. It is absent from larry skin, which has a mere background there.
Wouldn't it be better removing this empty space entirely?

**Comment by n3storm** [comment]
It would be better indeed.
Our approach is inherit from Larry so there is no screen unstyled and work only with css.
What you suggest cannot be done without creating a template file and creating templates is by now out of the scope of this theme, sorry.

**Comment by PF4Public** [comment]
Well, this issue could be closed now and preserved as a notice then.

**Comment by n3storm** [comment]
I now is sad, we don't like that empty space around.
