### ISSUE TITLE
Pop-ups not styled

### ISSUE THREAD

**Issue by PF4Public** [EstudioNexos/mabola#7]
Pop-ups are not styled. Namely "Loading" pop-up and top buttons' hint pop-ups.
Could be seen here for example:
![ff](https://cloud.githubusercontent.com/assets/10319700/14390554/5cdbac34-fdc0-11e5-91d4-4fc787946c3c.PNG)

**Comment by n3storm** [comment]
Those popups should not appear.
Are you sure you are using last mabola version?
What version of roundcube have you installed?

**Comment by PF4Public** [comment]
I have Roundcube 1.1.4
Those popups appear only in Firefox and Vivaldi for me.
They seem not to be appearing in old Opera.
Sure I use the latest Mabola version.

**Comment by n3storm** [comment]
@PF4Public this has been fixed with lastest commits.
