### ISSUE TITLE
Mobile-friendliness

### ISSUE THREAD

**Issue by PF4Public** [EstudioNexos/mabola#8]
Initially Larry skin is nearly broken for mobile devices with less-then-desktop screens.
Is it difficult it to fix this in mabola?

**Comment by n3storm** [comment]
It is :(
Better use a mobile only skin: https://github.com/messagerie-melanie2/Roundcube-Skin-Melanie2-Larry-Mobile/

**Comment by PF4Public** [comment]
Wow, thanks for pointing that out. I'll give it a try. 
Nonetheless mabola is still nice for using in desktop environment.
