### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by PF4Public** [EstudioNexos/mabola#9]
Wrong license is shown at the settings tab with skin selection. This repo says "Creative Commons Attribution-ShareAlike License", but Roundcube reports "GNU General Public License"

**Comment by n3storm** [comment]
Mabola skin is GPL, but is using Laclasse Icons from  https://github.com/laclasse-com/roundcube_laclasse_skin. and is why you read "Creative Commons Attribution-ShareAlike License." 

I have edited README file to avoid this confusion again.
